version: '3.8'
services:
    wahoo:
        image: 'redgreat/wahoo_webhook:latest'
        container_name: wahoo
        restart: unless-stopped
        ports:
            - '8080:8090'
        volumes:
            - ./config/config.yml:/code/app/config/config.yml
            - ./logs/:/code/app/logs/:rw
        environment:
            DISABLE_IPV6: 'true'
        deploy:
            resources:
                limits:
                    memory: 256M
                reservations:
                    memory: 8M
        mem_swappiness: 0
        oom_kill_disable: true
