version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: arq app.core.worker.settings.WorkerSettings
    env_file:
      - ./src/.env
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
